name = "Soyuz"
uuid = "54d5a12a-aad6-4518-97ed-809a73574565"
authors = ["キャンド <amehikoji@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Ekztazy = "c8b112a7-7677-4d35-8651-7c5b5cba290e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
